server:
  port: 8082

spring:
  application:
    name: EMERGENCY-SERVICE

  datasource:
    url: jdbc:mysql://localhost:3306/emergency_db?createDatabaseIfNotExist=true
    username: root
    password: p1u2n3e4e5t6
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: ifernenp39u424r9nfq29f4891fuxf4c981h8hzbfyxyq34bxfr
  expiration: 3600000

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      emergencyService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  retry:
    instances:
      emergencyService:
        maxAttempts: 3
        waitDuration: 2s

  timelimiter:
    instances:
      emergencyService:
        timeoutDuration: 3s



    