server:
  port: ${PORT:8083}

spring:
  application:
    name: EMERGENCY-SERVICE

  autoconfigure:
    exclude:
      - org.springframework.ai.model.chat.memory.redis.autoconfigure.RedisChatMemoryAutoConfiguration

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/emergency_service}
    username: ${DB_USERNAME:puneetagnihotri}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.postgresql.Driver}

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

  data:
    redis:
      host: localhost
      port: 6379

  data.web.pageable.max-page-size: 100
  data.web.pageable.default-page-size: 25

jwt:
  secret: ${JWT_SECRET:cmFrc2hhay1kZXYta2V5LW5vdC1mb3ItcHJvZA==}
  expiration: ${JWT_EXPIRATION:3600000}

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}
  instance:
    prefer-ip-address: true

resilience4j:
  circuitbreaker:
    instances:
      emergencyService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        failureRateThreshold: 50
        waitDurationInOpenState: 10s

  retry:
    instances:
      emergencyService:
        maxAttempts: 3
        waitDuration: 2s

  timelimiter:
    instances:
      emergencyService:
        timeoutDuration: 3s



    
