server:
  port: ${PORT:8082}

spring:
  application:
    name: dispatch-service

  datasource:
    url: jdbc:postgresql://localhost:5432/emergency_service
    username: puneetagnihotri
    password: 
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        acknowledge-mode: auto
        concurrency: 3
        max-concurrency: 10

  data:
    redis:
      host: localhost
      port: 6379

jwt:
  secret: ${JWT_SECRET:cmFrc2hhay1kZXYta2V5LW5vdC1mb3ItcHJvZA==}

# 🟢 Eureka Client Config
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

  instance:
    prefer-ip-address: true
    hostname: localhost

# 🔥 Resilience4j (for fault tolerance)
resilience4j:
  retry:
    instances:
      dispatchRetry:
        max-attempts: 3
        wait-duration: 2s

  circuitbreaker:
    instances:
      responderServiceCB:
        sliding-window-size: 10
        failure-rate-threshold: 50
        wait-duration-in-open-state: 10s

# Logging (important for debugging distributed systems)
logging:
  level:
    root: INFO
    com.emergency_service: DEBUG
