server:
  port: ${PORT:8086}

spring:
  application:
    name: notification-service

  datasource:
    url: ${DB_URL:jdbc:postgresql://localhost:5432/notification_service}
    username: ${DB_USERNAME:puneetagnihotri}
    password: ${DB_PASSWORD:}
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}
    listener:
      simple:
        acknowledge-mode: auto

  data.web.pageable.max-page-size: 100
  data.web.pageable.default-page-size: 25

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}

    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

eureka:
  client:
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,prometheus

jwt:
  secret: ${JWT_SECRET:cmFrc2hhay1kZXYta2V5LW5vdC1mb3ItcHJvZA==}
