server:
  port: ${PORT:8087}

spring:
  application:
    name: hospital-service
  autoconfigure:
    exclude:
      - org.springframework.boot.jdbc.autoconfigure.DataSourceAutoConfiguration
      - org.springframework.boot.hibernate.autoconfigure.HibernateJpaAutoConfiguration

  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:guest}
    password: ${RABBITMQ_PASSWORD:guest}

jwt:
  secret: ${JWT_SECRET:cmFrc2hhay1kZXYta2V5LW5vdC1mb3ItcHJvZA==}

openroute:
  api-key: ${OPENROUTE_API_KEY:}
  url: ${OPENROUTE_URL:https://api.openrouteservice.org/v2/directions/driving-car/geojson}

eureka:
  client:
    enabled: false
    service-url:
      defaultZone: ${EUREKA_URL:http://localhost:8761/eureka/}


overpass:
  url: https://overpass.kumi.systems/api/interpreter
  radius: 500

# https://overpass-api.de/api/interpreter
